name: Build da imagem e envio para Dockerhub
on: 
  push:
    banches: [ main ]
  workflow_dispatch:

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repost√≥riio
        uses: actions/checkout@v4

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem e push para DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-app:latest
