name: Build da imagem e envio para Dockerhub
on: 
  #push:
   # branches: [ main ]
  workflow_dispatch:

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repostóriio
        uses: actions/checkout@v4

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem e push para DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/simple-app:latest
            ${{ secrets.DOCKER_USERNAME }}/simple-app:v${{ github.sha }}
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      #Action para conexão com chave primária SSH
      - name: Setup SSH for manifests repo
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #Aqui será feito o clone do repositório do manifest, alterando a versão da imagem docker 
      - name: Update manifest YAML
        run: |
          git clone git@github.com:DonaMaxii/simple-app-manifests.git
          cd simple-app-manifests/k8s
          sed -i "s|image: donamaxii/simple-app:.*|image: donamaxii/simple-app:v${{ github.sha }}|" simple-app-manifest.yaml
      # Aqui será realizado commit para manifest repo
      - name: Commit with PR to manifest repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add simple-app-manifest.yaml
          git commit -m "update: image v${{ github.sha }}"
          git push origin main